In [1]:
import numpy as np
import torch
import torch.nn as nn

Excercise 2

In [2]:
input = np.array([[75, 72, 40], 
                            [100, 89, 68], 
                            [85, 120, 62], 
                            [95, 55, 39], 
                            [65, 90, 75], 
                            [83, 72, 56], 
                            [81, 88, 75], 
                            [78, 114, 99], 
                            [98, 51, 57], 
                            [69, 96, 71], 
                            [79, 76, 54], 
                            [72, 77, 84], 
                            [67, 125, 67], 
                            [100, 53, 46], 
                            [70, 107, 60]], 
                            dtype='float32')

# Targets (apples, oranges)
target = np.array([[54, 75], 
                              [79, 121], 
                              [105, 130], 
                              [33, 39], 
                              [101, 110],
                              [45, 79], 
                              [85, 92], 
                              [110, 122], 
                              [36, 35], 
                              [95, 114], 
                              [57, 69], 
                              [82, 100], 
                              [118, 134], 
                              [20, 38], 
                              [102, 120]], 
                              dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

In [3]:
from torch.utils.data import TensorDataset

In [4]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 75.,  72.,  40.],
         [100.,  89.,  68.],
         [ 85., 120.,  62.]]), tensor([[ 54.,  75.],
         [ 79., 121.],
         [105., 130.]]))

In [12]:
from torch.utils.data import DataLoader
batch_size = 5

#dataloader of tenser data

train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [9]:
#model define

model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1012,  0.2470, -0.5243],
        [ 0.2192,  0.4620,  0.0821]], requires_grad=True)
Parameter containing:
tensor([ 0.3939, -0.0251], requires_grad=True)


In [8]:
#convert into parameters

list(model.parameters())

[Parameter containing:
 tensor([[ 0.5223,  0.5635,  0.4284],
         [ 0.1943, -0.2811,  0.2082]], requires_grad=True),
 Parameter containing:
 tensor([0.0132, 0.0054], requires_grad=True)]

In [11]:
import torch.nn.functional as F
loss_fn = F.mse_loss

# //we use model of toarch


loss = loss_fn(model(inputs), targets)  #mse loss
print(loss)
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

tensor(4323.7085, grad_fn=<MseLossBackward0>)


In [14]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
      
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

fit(100,model,loss_fn,opt,train_dl)

Epoch [1/100], Loss: 3372.0913
Epoch [2/100], Loss: 1645.8344
Epoch [3/100], Loss: 464.6747
Epoch [4/100], Loss: 536.0237
Epoch [5/100], Loss: 886.9552
Epoch [6/100], Loss: 682.5856
Epoch [7/100], Loss: 249.0524
Epoch [8/100], Loss: 673.8196
Epoch [9/100], Loss: 401.7143
Epoch [10/100], Loss: 878.4837
Epoch [11/100], Loss: 283.8185
Epoch [12/100], Loss: 343.6934
Epoch [13/100], Loss: 649.8130
Epoch [14/100], Loss: 593.8961
Epoch [15/100], Loss: 191.2742
Epoch [16/100], Loss: 225.7074
Epoch [17/100], Loss: 348.9149
Epoch [18/100], Loss: 311.8343
Epoch [19/100], Loss: 478.3224
Epoch [20/100], Loss: 185.9585
Epoch [21/100], Loss: 324.9532
Epoch [22/100], Loss: 423.8699
Epoch [23/100], Loss: 283.1068
Epoch [24/100], Loss: 135.8713
Epoch [25/100], Loss: 220.0447
Epoch [26/100], Loss: 258.8709
Epoch [27/100], Loss: 164.8512
Epoch [28/100], Loss: 336.0184
Epoch [29/100], Loss: 216.7875
Epoch [30/100], Loss: 269.0617
Epoch [31/100], Loss: 197.9279
Epoch [32/100], Loss: 286.0739
Epoch [33/100],

In [16]:
# Generate predictions
preds = model(inputs)
preds


# Compare with targets
k=0
for i in preds:
  print("prediction : ",i," Target : ",targets[k])
  k+=1

prediction :  tensor([60.7966, 72.2319], grad_fn=<UnbindBackward0>)  Target :  tensor([54., 75.])
prediction :  tensor([75.1335, 93.6361], grad_fn=<UnbindBackward0>)  Target :  tensor([ 79., 121.])
prediction :  tensor([108.7259, 125.4121], grad_fn=<UnbindBackward0>)  Target :  tensor([105., 130.])
prediction :  tensor([39.6488, 51.6506], grad_fn=<UnbindBackward0>)  Target :  tensor([33., 39.])
prediction :  tensor([ 83.7611, 102.3136], grad_fn=<UnbindBackward0>)  Target :  tensor([101., 110.])
prediction :  tensor([60.5169, 75.7032], grad_fn=<UnbindBackward0>)  Target :  tensor([45., 79.])
prediction :  tensor([78.5366, 97.7459], grad_fn=<UnbindBackward0>)  Target :  tensor([85., 92.])
prediction :  tensor([107.1967, 131.4845], grad_fn=<UnbindBackward0>)  Target :  tensor([110., 122.])
prediction :  tensor([36.5322, 52.4943], grad_fn=<UnbindBackward0>)  Target :  tensor([36., 35.])
prediction :  tensor([ 88.6376, 106.5177], grad_fn=<UnbindBackward0>)  Target :  tensor([ 95., 114.])
pr

In [17]:
#optimizer function
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

