In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')
data=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Dataset2.csv')
print(data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


#task1

In [4]:
#oneHotEncoding of features:
from sklearn.preprocessing import OneHotEncoder


In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder

X = data.iloc[:, :-1].values 
  
# Only last column  
Y = data.iloc[:, -1].values

data_train, data_test, target_train, target_test = train_test_split(X,
Y, test_size = 0.25, random_state = 98)

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

import numpy as np
gnb = GaussianNB()

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

data_train_ohe = ohe.fit_transform(data_train)
data_test_ohe = ohe.fit_transform(data_test)
#Train the model using the training sets
gnb.fit(data_train_ohe, target_train)
#Predict the response for test dataset
data_test_ohe
# target_pred = gnb.predict(data_test_ohe)
# print(target_pred)

# precision = precisison_score(target_test, target_pred,average=None)
# recall = recall_score(target_test, target_pred,average=None)
# print('precision: {}'.format(precision))
# print('recall: {}'.format(recall))


array([[1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 1., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 1.]])

Task2

In [19]:
 #Import scikit-learn dataset library
from sklearn import datasets

wine=datasets.load_wine()
print(wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [20]:
# print the names of the 13 features
print("Features: ", wine.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine.target_names)
# print data(feature)shape
wine.data.shape

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']


(178, 13)

In [21]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test,target_train,target_test= train_test_split(wine.data,
wine.target, test_size = 0.20, random_state = 98)

In [22]:
print(data_train)
print(data_test)
print(target_test)
print(target_train)

[[1.260e+01 2.460e+00 2.200e+00 ... 7.300e-01 1.580e+00 6.950e+02]
 [1.369e+01 3.260e+00 2.540e+00 ... 9.600e-01 1.820e+00 6.800e+02]
 [1.141e+01 7.400e-01 2.500e+00 ... 1.100e+00 2.310e+00 4.340e+02]
 ...
 [1.237e+01 1.210e+00 2.560e+00 ... 1.190e+00 2.300e+00 6.780e+02]
 [1.200e+01 1.510e+00 2.420e+00 ... 1.050e+00 2.650e+00 4.500e+02]
 [1.388e+01 1.890e+00 2.590e+00 ... 8.800e-01 3.560e+00 1.095e+03]]
[[1.422e+01 1.700e+00 2.300e+00 1.630e+01 1.180e+02 3.200e+00 3.000e+00
  2.600e-01 2.030e+00 6.380e+00 9.400e-01 3.310e+00 9.700e+02]
 [1.162e+01 1.990e+00 2.280e+00 1.800e+01 9.800e+01 3.020e+00 2.260e+00
  1.700e-01 1.350e+00 3.250e+00 1.160e+00 2.960e+00 3.450e+02]
 [1.303e+01 9.000e-01 1.710e+00 1.600e+01 8.600e+01 1.950e+00 2.030e+00
  2.400e-01 1.460e+00 4.600e+00 1.190e+00 2.480e+00 3.920e+02]
 [1.267e+01 9.800e-01 2.240e+00 1.800e+01 9.900e+01 2.200e+00 1.940e+00
  3.000e-01 1.460e+00 2.620e+00 1.230e+00 3.160e+00 4.500e+02]
 [1.217e+01 1.450e+00 2.530e+00 1.900e+01 1.040e+02 

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
data_train_ohe = ohe.fit_transform(data_train)
print(data_train_ohe)
data_test_ohe = ohe.fit_transform(data_test)
print(data_test_ohe)

In [24]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [25]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print(target_test)
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

[0 1 1 1 1 2 0 2 1 0 1 1 1 1 1 2 0 1 1 1 1 0 0 2 2 1 1 1 0 1 1 0 0 0 0 1]
Accuracy: 0.9722222222222222


In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[11,  0,  0],
       [ 0, 19,  1],
       [ 0,  0,  5]])

In [27]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         1.         0.83333333]
recall: [1.   0.95 1.  ]
