standaraliation with minmaxscaler and standard scalar


In [ ]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Step 2: Load Data
from google.colab import drive
drive.mount('/content/drive')

datasets = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Exercise-CarData.csv') 
datasets.head()

Mounted at /content/drive


Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0           0  13500  23.0  46986  ...         0  2000  three    1165
1           1  13750  23.0  72937  ...         0  2000      3    1165
2           2  13950  24.0  41711  ...         0  2000      3    1165
3           3  14950  26.0  48000  ...         0  2000      3    1165
4           4  13750  30.0  38500  ...         0  2000      3    1170

[5 rows x 11 columns]

In [ ]:
# Step 3: Seprate Input and Output attributes

# All rows, all columns except last 
X = datasets.iloc[:, :-1].values 
  
# Only last column  
Y = datasets.iloc[:, -1].values 

print("\n\nInput : \n", X) 
print("\n\nOutput: \n", Y) 



Input : 
 [[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


Output: 
 [1165 1165 1165 ... 1015 1015 1114]


In [ ]:

X_new = datasets.iloc[:,1:3].values
print("\n\nX for transformation : \n", X_new)



X for transformation : 
 [[13500.    23.]
 [13750.    23.]
 [13950.    24.]
 ...
 [ 8500.    nan]
 [ 7250.    70.]
 [ 6950.    76.]]


In [ ]:
# Step 5 : Perform standardization on age and salary

std = StandardScaler()
X_std = std.fit_transform(X_new)
print("\n\nStandardized X : \n", X_std)



Standardized X : 
 [[ 0.76376268 -1.75818903]
 [ 0.83271485 -1.75818903]
 [ 0.88787659 -1.70437596]
 ...
 [-0.6152808          nan]
 [-0.96004167  0.7710253 ]
 [-1.04278428  1.09390373]]
