1. Create a Numpy array of size 4 x 5.
2.  Randomly initialize the array.

In [1]:
import numpy as np

In [25]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
list4=[16,17,18,19,20]
arr1=np.array([list1,list2,list3,list4])
print(arr1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


3. Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [14]:
arr2=arr1.T
print("transpose of matrix arr1\n" , arr2)



squareM=np.array([[1,2,7],[7,5,6],[7,8,9]])
print("Square matrix\n",squareM)
print("\nDeterminant of square matrix M\n",np.linalg.det(squareM))

transpose of matrix arr1
 [[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
Square matrix
 [[1 2 7]
 [7 5 6]
 [7 8 9]]

Determinant of square matrix M
 102.00000000000004


4. Create another matrix of size 5 x 4 and randomly initialize it.

In [16]:
list1=[1,2,3,4]
list2=[6,7,8,9]
list3=[11,12,13,14]
list4=[16,17,18,19]
list5=[5,10,15,20]
arr2=np.array([list1,list2,list3,list4,list5])
print(arr2)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [ 5 10 15 20]]


5. Perform Matrix multiplication.

In [22]:
multiplicationM=np.dot(squareM,squareM)
print("multiplication\n",multiplicationM)

multiplication
 [[ 64  68  82]
 [ 84  87 133]
 [126 126 178]]


6. Perform element wise matrix multiplication.

In [26]:
arr3=arr1*arr1
print(arr3)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


7. Find mean, median of the numpy array created.

In [31]:
mean = np.mean(squareM) 
print("mean = ",mean)

median=np.median(squareM)
print("\nmedian = ",median)

mean =  5.777777777777778

median =  7.0


8. Obtain each row in the second column of the first array.

In [34]:
col2=arr1[:,1]
print(col2)

[ 2  7 12 17]


9. Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
#!ls "/content/drive/My Drive/Colab Notebooks"
data=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Iris.csv')
print(data - np.mean(data,axis=0))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
       Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species
0   -74.5      -2.358667     -0.998667      -0.743333         0.446     NaN
1   -73.5      -2.358667     -0.998667      -0.943333        -0.054     NaN
2   -72.5      -2.458667     -0.998667      -1.143333         0.146     NaN
3   -71.5      -2.258667     -0.998667      -1.243333         0.046     NaN
4   -70.5      -2.358667     -0.998667      -0.843333         0.546     NaN
..    ...            ...           ...            ...           ...     ...
145  70.5       1.441333      1.101333       0.856667        -0.054     NaN
146  71.5       1.241333      0.701333       0.456667        -0.554     NaN
147  72.5       1.441333      0.801333       0.656667        -0.054     NaN
148  73.5       1.641333      1.101333       0.356667         0.346     NaN
149  74.5       1.341333      0.601

10. Study about numpy array attributes and implement it on the first matrix.

In [48]:
sum=np.array([1,2,3])+np.array([4,5,6])
print("sum= ",sum)

sum=  [5 7 9]
